<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<LangVersion>preview</LangVersion>
		<UserSecretsId>ed31f171-71e0-4158-8732-1ef7532f0c30</UserSecretsId>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Google.Apis.Auth" Version="1.76.0" />
		<PackageReference Include="Google.Apis.Sheets.v4" Version="1.75.0.4178" />
		<PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.11" />
		<PackageReference Include="NetCord.Hosting" Version="1.0.0-beta.18" />
		<PackageReference Include="NetCord.Hosting.Services" Version="1.0.0-beta.18" />
		<PackageReference Include="NetCord.Services" Version="1.0.0-beta.18" />
	</ItemGroup>

	<ItemGroup>
		<None Update="appsettings.json">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="credential.json">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>

	<ItemGroup>
		<Content Include="Localizations\**\*.json">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="Ichihime\LocalizeSystem\" />
	</ItemGroup>

</Project>
